### PR TITLE
feat(vm_size): Updates vm sizes to state at 2024-06-11

### PR DESCRIPTION
**Pull request by JannoTjarks**
Hello, this PR updates the valid vm sizes. There are 13 more sizes available that are currently specified in this rule set.
I got the sizes from the script of the PR #338.

### CODE REVIEW

**Comment by wata727** [comment]
Thank you for your contribution!
After reviewing the diff, it appears that the following machine types will be removed:

- Standard_A8
- Standard_A9
- Standard_A10
- Standard_A11
- Standard_DC2s
- Standard_DC4s
- Standard_NC6s_v2
- Standard_NC12s_v2
- Standard_NC24s_v2
- Standard_NC24rs_v2
- Standard_ND6s
- Standard_ND12s
- Standard_ND24s
- Standard_ND24rs

It's probably related to the retirement, but I'm not sure if it's OK to remove them from the available machine types at this point.
https://learn.microsoft.com/en-us/azure/virtual-machines/sizes/previous-gen-sizes-list

What do you think?

**Comment by JannoTjarks** [comment]
Hi @wata727, that's the reason, why a 4-eye principle is a good thing!
I got the list by the script I contributed in the Pr [#338](https://github.com/terraform-linters/tflint-ruleset-azurerm/issues/338).

I will check, if there is also an automated way to get also the retired sizes.

Will keep you updated!

**Comment by JannoTjarks** [comment]
@wata727 The retired images are now back into the slice.
I didnt find a way to request the retired sizes per api. So from now i will just append on the slice with new sizes. Maybe in the future i could work on a cleanup task for the slice. 
One idea would be to return a Warning, if the the image is mentioned is on retirement or not usable anymore. 

What is your opinion on this? But this seems to need be done manual...

**Comment by wata727** [comment]
Thank you for working on this. It's unfortunate that there's no automated way to do this, but the PR is worth merging anyway.

> One idea would be to return a Warning, if the the image is mentioned is on retirement or not usable anymore.

This might be worth it in itself. The AWS ruleset has a rule that warn against previous generation instance types.
https://github.com/terraform-linters/tflint-ruleset-aws/blob/v0.32.0/docs/rules/aws_instance_previous_type.md

**Review by wata727 — APPROVED** [review]

**Pull request merged**
